### ISSUE TITLE
Support for NLP Tasks 

### ISSUE THREAD

**Issue by anishacharya** [microsoft/OpenMSFTL#5]
Support for NLP Tasks 
We would like to add support for nlp tasks. Ideally, follow the vision_datasets.py implementation and do a parallel implementation, The output should be similar to that of vision_datasets, so I am guessing one of the two ways: use torchnlp and create dataloaders. Or, use our own embedding , indexer etc. For reference feel free to re-use my earlier implementations:
https://github.com/anishacharya/nlp-done-right/tree/master/common/utils

**Comment by kkumatani** [comment]
done
